export const HOME_PAGE_PRESENTATION_SHOW_FAVORITES_TITLE_KEY: string =
  'homePagePresentationShowFavoritesTitle';
export const HOME_PAGE_PRESENTATION_SHOW_SHORTCUT_NAMES_KEY: string =
  'homePagePresentationShowShortcutNames';
export const HOME_PAGE_PRESENTATION_SHOW_RECENTLY_CLOSED_TITLE_KEY: string =
  'homePagePresentationShowRecentlyClosedTitle';
export const HOME_PAGE_PRESENTATION_SHOW_SETTINGS_BUTTON_KEY: string =
  'homePagePresentationShowSettingsButton';
export const HOME_PAGE_PRESENTATION_HOME_PAGE_STYLE_KEY: string =
  'homePagePresentationHomePageStyle';
export const HOME_PAGE_PRESENTATION_HOME_LOGO_ID_KEY: string =
  'homePagePresentationHomeLogoId';
export const HOME_PAGE_PRESENTATION_HOME_LOGO_CUSTOM_URI_KEY: string =
  'homePagePresentationHomeLogoCustomUri';
export const HOME_PAGE_PRESENTATION_HOME_LOGO_CUSTOM_WIDTH_KEY: string =
  'homePagePresentationHomeLogoCustomWidth';
export const HOME_PAGE_PRESENTATION_HOME_LOGO_CUSTOM_HEIGHT_KEY: string =
  'homePagePresentationHomeLogoCustomHeight';
export const HOME_PAGE_PRESENTATION_HOME_LOGO_SCALE_RATIO_KEY: string =
  'homePagePresentationHomeLogoScaleRatio';
export const HOME_PAGE_PRESENTATION_HOME_LOGO_OPACITY_KEY: string =
  'homePagePresentationHomeLogoOpacity';
